### ISSUE TITLE
Butternut instead of Uglify

### ISSUE THREAD

**Issue by Swizz** [egoist/bili#11]
What about using Butternut ? 

To make Bili the right tool for @Rich-Harris aficionados :+1: 

Isnt it too young for you ?

**Comment by egoist** [comment]
Yeah, it's a little early, but definitely will consider that when it's more stable.

**Comment by Swizz** [comment]
I am glad to read this ! Thank you

**Comment by Swizz** [comment]
I know this is pretty offtopic but Thank you for bili, I use it all day long for quick prototyping :+1:

**Comment by egoist** [comment]
@Swizz thanks for the kind words 👌

**Comment by egoist** [comment]
Seems it's no longer actively maintained? So I'm closing this for now.

BTW we're using [`uglify-es`](https://egoist.moe/bili/#/api?id=uglifyes) by default now.
