### ISSUE TITLE
(babel) This API has been removed. If you're looking for this functionality in Babel 7, you should imp ort the '@babel/helper-module-imports' module and use the functions exposed  from that module, such as 'ad dNamed' or 'addDefault'.

### ISSUE THREAD

**Issue by fjc0k** [egoist/bili#112]
https://github.com/vuejs/babel-plugin-transform-vue-jsx/issues/112

**Comment by egoist** [comment]
@fjc0k yeah we need to remove some plugins that are not compatible with babel 7

**Comment by fjc0k** [comment]
maybe we should update the dependency: `babel-plugin-transform-vue-jsx`

**Comment by egoist** [comment]
could you make a PR?

**Comment by fjc0k** [comment]
let me see see....

**Comment by fjc0k** [comment]
https://github.com/vuejs/babel-preset-vue/pull/9

**Comment by fjc0k** [comment]
@egoist https://github.com/vuejs/babel-preset-vue/pull/9

**Comment by egoist** [comment]
Fixed in `v3.0.14`
