### ISSUE TITLE
scoped style not working

### ISSUE THREAD

**Issue by gigioSouza** [egoist/bili#115]
To the given component:
```
<template>
  <div>
    Test status: {{ status }}
  </div>
</template>

<script>
  export default {
    props: ['status']
  }
</script>

<style scoped lang="scss">
  div {
    background-color: yellow;
    color: blue;
  }
</style>
```

The generated `.css` is:
```
div {
  background-color: yellow;
  color: blue; 
}
```

I'm using:
```
"bili": "^3.0.15",
"node-sass": "^4.8.3",
"rollup-plugin-vue": "^3.0.0",
"vue-template-compiler": "^2.5.16"
```

`bili.config.js`:
```
module.exports = {
  banner: true,
  format: ['umd', 'umd-min', 'cjs', 'es'],
  plugins: ['vue']
}
```

I found out this workaround in your twitter: https://twitter.com/_egoistlily/status/980637506382123009

Are you working in something automated?

**Comment by znck** [comment]
It would break it as the scope ID should be same in template and style.

**Comment by gigioSouza** [comment]
@znck Actually I tested as is suggested in the tweet and it worked. The template id was using the same as I setted in the `_scopeId` attribute.

But I found the solution for this problem, in my `bili.config.js` instead of this:
```
module.exports = {
  banner: true,
  format: ['umd', 'umd-min', 'cjs', 'es'],
  plugins: ['vue']
}
```
configuring like this it worked:
```
const vue = require('rollup-plugin-vue');

module.exports = {
  banner: true,
  format: ['umd', 'umd-min', 'cjs', 'es'],
  plugins: [
    vue({
      css: true // or using string for external .css
    })
  ],
};
```
