### ISSUE TITLE
`buble.transforms` gets deleted after compiling first target

### ISSUE THREAD

**Issue by queckezz** [egoist/bili#13]
Given this `bili.config.js`:
```js
module.exports = {
  format: ['cjs', 'es'],
  buble: {
    transforms: {
      dangerousTaggedTemplateString: true
    }
  }
}
```

It won't pickup `buble.transforms` for the `es` build because you seem to delete them at [./get-rollup-options.js#L43](https://github.com/egoist/bili/blob/master/src/get-rollup-options.js#L43) after the `cjs` build.

So for every subsequent target it compiles without the transform options.

**Comment by egoist** [comment]
Thanks, `v0.15.5` is released.
