### ISSUE TITLE
Bili by changing the typescript code of .d.ts files

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [egoist/bili#138]
Hello
I'm using bili in a typescript project that generates the definitions automatically, the result looks like this
```js
export declare type verifierDigit = (digits: string) => number;
export declare type strip = (number: string, strict?: boolean) => string;
export declare type format = (number: string) => string;
export declare type isValid = (number: string, strict?: boolean) => boolean;
export declare type generate = (formatted?: boolean) => string;
declare const _default: {
    verifierDigit: verifierDigit;
    strip: strip;
    format: format;
    isValid: isValid;
    generate: generate;
};
export default _default;
```
When I run the tests, the bili alters code above and generates a different one, the code stays that way.
```js
declare const _default: {
    verifierDigit: (digits: any) => number;
    strip: (number: any, strict: any) => any;
    format: (number: any) => any;
    isValid: (number: any, strict: any) => boolean;
    generate: (formatted: any) => any;
};
export default _default;
```
maybe this behavior is standard, but for typescript definitions I need this `.d.ts` code to remain unchanged

how can i configure the bili not to do this?

the example code can be downloaded from this [link here](https://github.com/carvalhoviniciusluiz/cpf-cnpj-validator)

**Comment by egoist** [comment]
Hi, I'm no typescript expert but the only thing bili did for typescript support is using `rollup-plugin-typescript` (in your case)

**Comment by carvalhoviniciusluiz** [comment]
the other lib is making that change? I understood, I'll check.
thank you
