### ISSUE TITLE
The latest version cannot generate compressed files

### ISSUE THREAD

**Issue by u3u** [egoist/bili#147]
(uglify) Unexpected token: keyword (const)

bili version: v3.3.0

**Comment by egoist** [comment]
Are you using a custom babel config file? seems that the `const` is not compiled to `var`

**Comment by u3u** [comment]
I am using rollup-plugin-typescript2

**Comment by u3u** [comment]
@egoist Yes, I set `compilerOptions.target` to `esnext`, but it works fine in bili v3.2.0

**Comment by egoist** [comment]
oh seems rollup-plugin-uglify v3 (bili previously used) can actually minify es6 code but now removed es6 support, I'm switching to rollup-plugin-terser then.

**Comment by egoist** [comment]
Fixed in v3.3.1
