### ISSUE TITLE
Can't extract CSS to single file

### ISSUE THREAD

**Issue by rchl** [egoist/bili#157]
[rollup-plugin-postcss](https://github.com/egoist/rollup-plugin-postcss) supports specifying string for `extract` option to extract all CSS to single file. In Bili, passing string to `extract` is handled same as 'true' value due to onExtract function [being overridden](https://github.com/egoist/bili/blob/f7615dbc25fcc6eef82c0197f5d24eb10212f042/src/index.js#L406).

Is there any hope that extracting to single CSS file will be supported? Maybe it would need to be reimplemented in Bili to support all use cases.

**Comment by egoist** [comment]
> Is there any hope that extracting to single CSS file will be supported?

isn't that the current behavior? I think what you want is custom CSS output file?

> Maybe it would need to be reimplemented in Bili to support all use cases

What's your use case?

**Comment by rchl** [comment]
My configuration includes `"input": "components/**/*.vue",` which results in creating separate js file for each component. It also creates css file for components that have CSS. I would prefer to have one CSS file for all components to simplify use of that package -- no need to specify in the readme or somewhere, for which components it's necessary to include CSS.

**Comment by egoist** [comment]
Well allowing to specify string for `extract` option won't help with your use case, when `input` is a glob pattern like `components/**/*.vue` each file is bundled in a separate process, i.e. multiple Rollup builds.

You can either manually concat those CSS files into one file after running `bili`, or export all your components in a single file and use it as the Bili entry file.
