### ISSUE TITLE
Bili vs Microbundle

### ISSUE THREAD

**Issue by aleclarson** [egoist/bili#163]
@egoist I'm curious what you think of [microbundle](https://github.com/developit/microbundle) and how Bili differs from it. :)

**Comment by hosein2398** [comment]
If you want my view,
- Bili is more optionated in CLI commands
- supports Vue
- better docs
- Bili can have a seprate config file

**Comment by egoist** [comment]
microbundle is more opinionated (which isn't a bad thing), bili gives you more options.

btw I just rewrote this in typescript, you can even use bili.config.ts out-of-the-box now https://bili.egoist.sh/#/configuration-file

and even better API docs https://bili.egoist.sh/api/interfaces/config.html

**Comment by aleclarson** [comment]
@egoist Awesome. Thanks for the reply!
