### ISSUE TITLE
Vue file isn't watched when in watch-mode.

### ISSUE THREAD

**Issue by seehat** [egoist/bili#170]
I import a .vue file into the compiled and watched index.js file. 
Only changes in the index.js file and other imported js files are recognized, but no changes of the .vue file. 

Can I change the watch options of rollup somehow?

**Comment by egoist** [comment]
@seehat That's an issue with rollup-plugin-vue

**Comment by seehat** [comment]
Wow this was fast. Ok thx.

**Comment by seehat** [comment]
Closed.
