### ISSUE TITLE
How to use bili for unit test?

### ISSUE THREAD

**Issue by brandonxiang** [egoist/bili#178]
- How to use bili for unit test?
- Could I use it with jest?

**Comment by egoist** [comment]
you can use jest directly to test your source files.

**Comment by brandonxiang** [comment]
Jest will detect babel.config.js, but at the root of my project, there is no babel configuration. Meanwhile, there is no babel-pre-env dependencies in my packages either.

**Comment by egoist** [comment]
Just add one? https://bili.egoist.sh/#/recipes/javascript#babel
