### ISSUE TITLE
globbed input no longer works in v4?

### ISSUE THREAD

**Issue by adamlohner** [egoist/bili#180]
Struggling to migrate from v3-v4... It looks like using globs for the input is no longer supported in v4? Is there another way to achieve this same recipe found in v3?
```
bili "src/*.js" --filename "[name].js"
```
If not, might be worthwhile to add it to the migration guide since it's a core example in v3. 

Regardless, thanks for all the awesome work on this package!

**Comment by egoist** [comment]
Yeah it's removed, what's your use case of the glob input? Do you have many files in `./src` to bundle?

**Comment by adamlohner** [comment]
Pretty much. I was basically using `src/**/*.vue` to bundle a bunch of components exported as their own individual es modules. I can likely write a script to build the input array that I pass to bili, just wanted to make sure I wasn't missing something obvious before going down that route.

**Comment by egoist** [comment]
@adamlohner I'll clarify this in the migration guide, thanks for reporting.
