### ISSUE TITLE
node-resolve deprecated warnings in build

### ISSUE THREAD

**Issue by coderdiaz** [egoist/bili#181]
Hi @egoist,

I'm using Bili for bundle my Vue Libraries and Components but in the `build` process, Bili shows the next `deprecated` messages.

![image](https://user-images.githubusercontent.com/1901273/55667116-76129e80-5815-11e9-9606-bf75ba6d25a4.png)

Cheers,

**Comment by zcuric** [comment]
👍

**Comment by hosein2398** [comment]
Which version of Bili you are using?
I think this is resolved in v4.7.4

**Comment by fi3ework** [comment]
Yes, it's resolved in v4.7.4
