### ISSUE TITLE
Cannot specify `strict` option of Rollup.

### ISSUE THREAD

**Issue by ulivz** [egoist/bili#188]
See:

- https://rollupjs.org/guide/en#command-line-reference
- https://github.com/egoist/bili/blob/master/src/index.ts#L453

I cannot find any backdoor to set it.

**Comment by egoist** [comment]
Why do you need this?

**Comment by ulivz** [comment]
Not me. But someone need it.

**Comment by egoist** [comment]
I mean the use case 😄

**Comment by ulivz** [comment]
Someone used bili to build her library, and met this error:

```
strict mode does not allow function declarations in a lexically nested statement
```

We cannot find any solution to solve it, so the worst solution is to disable `strict` mode. 😂

**Comment by egoist** [comment]
Try [extendRollupConfig](https://bili.egoist.sh/api/interfaces/config.html#extendrollupconfig) then:

```js
module.exports = {
  extendRollupConfig(config) {
	config.output.strict = false
    return config
  }
}
```

**Comment by ulivz** [comment]
Got it!

**Comment by ulivz** [comment]
OMG, This triggered an issue in production.


![image](https://user-images.githubusercontent.com/23133919/57775734-4928a400-7750-11e9-89d1-a4ac9fa7ebc6.png)

![image](https://user-images.githubusercontent.com/23133919/57775768-5b0a4700-7750-11e9-884b-5742e96b73cf.png)
