### ISSUE TITLE
error: Unknown option `--babel.babelrc`

### ISSUE THREAD

**Issue by ulivz** [egoist/bili#189]
![image](https://user-images.githubusercontent.com/23133919/57689822-dbf31100-7672-11e9-8dbc-7bc0c875e732.png)

```bash
$ bili --format umd,esm --no-babel.babelrc
yarn run v1.9.4
error: Unknown option `--babel.babelrc`

$ cat node_modules/bili/package.json | grep version
  "version": "4.7.4",
```

**Comment by egoist** [comment]
There's no such CLI flag in v4, use the config option `babel` instead: https://bili.egoist.sh/api/interfaces/config.html#babel

**Comment by ulivz** [comment]
Wow, I just checked out docs here. https://bili.egoist.sh/#/recipes/javascript#babel

**Comment by egoist** [comment]
@ulivz Forgot to update that part.
