### ISSUE TITLE
Automatically replace `process.env.NODE_ENV`

### ISSUE THREAD

**Issue by egoist** [egoist/bili#19]
With `--replace-env` option it automatically replace `process.env.NODE_ENV` depending on the format:

- `cjs` `es`: will not replace
- `umd/iife`: replace with `development`
- `compress`: replace with `production`

**Comment by egoist** [comment]
I think this could be the default behavior, with `replaceNodeEnv: false` you can disable it.

**Comment by egoist** [comment]
It's replaced in `bili serve` command.

**Comment by egoist** [comment]
It's set in `umd` `iife` format, need to document this in 2.0

https://github.com/egoist/bili/blob/881ff35e0cc4ddb3302015344d536c10246632bb/src/index.js#L208-L213

**Comment by CrashyBang** [comment]
Hey @egoist,

Is this still supported?

Cheers.
