### ISSUE TITLE
Cannot set `format` via `bili.config.js`

### ISSUE THREAD

**Issue by ulivz** [egoist/bili#191]
## Step to reproduce

```js
// bili.config.js
module.exports = {
  output: {
    moduleName: 'checkDowngrade',
    fileName: 'checkDowngrade.[format][min].js'
  },
  format: [
    'esm',
    'umd',
    'cjs',
    'cjs-min',
  ]
};
```

Buiild output:

![image](https://user-images.githubusercontent.com/23133919/57692254-e7e1d180-7678-11e9-82e7-8ac5e849db12.png)

**Comment by egoist** [comment]
`output.format`, you can use `bili.config.ts` to prevent from using unknown options: https://bili.egoist.sh/#/configuration-file#typescript

**Comment by ulivz** [comment]
Cool~
