### ISSUE TITLE
cjs format bulid bug

### ISSUE THREAD

**Issue by xgqfrms** [egoist/bili#194]
# cjs format bulid bug

![image](https://user-images.githubusercontent.com/7291672/58299684-8eb13500-7e12-11e9-977c-204d085953f8.png)

**Comment by xgqfrms** [comment]
#  full source codes

https://github.com/xgqfrms/xyz-button

**Comment by egoist** [comment]
The syntax to load plugins via CLI flag is `--plugin.vue` now

https://bili.egoist.sh/#/plugins

**Comment by xgqfrms** [comment]
@egoist 

not work still, what's wrong with it?

![image](https://user-images.githubusercontent.com/7291672/58299962-683fc980-7e13-11e9-82b1-679b972699d9.png)

**Comment by xgqfrms** [comment]
# default is OK

> no need set file path `src/index` & format flag `--format cjs`


![image](https://user-images.githubusercontent.com/7291672/58300303-94a81580-7e14-11e9-928c-f4a2a39fa4ca.png)


![image](https://user-images.githubusercontent.com/7291672/58300232-53b00100-7e14-11e9-8060-a59063ce1441.png)

**Comment by xgqfrms** [comment]
@egoist Thanks for your time!

**Comment by egoist** [comment]
Remove the quote `'` around your `'src/index.js'`, probably it's an Windows issue.

btw you don't need to include the plugin twice.

**Comment by xgqfrms** [comment]
# that's ok

![image](https://user-images.githubusercontent.com/7291672/58300614-db4a3f80-7e15-11e9-9ba0-d65fd043c1fe.png)

> btw you don't need to include the plugin twice.

you mean, bili will auto load `bili.config.js`, not need add it in npm script parms list?

**Comment by egoist** [comment]
yeah, use either cli flag or config file, no need for both

**Comment by xgqfrms** [comment]
OK, I'd like using the `bili.config.js`, it's more easy read & write.

Thanks a lot!

**Comment by xgqfrms** [comment]
what's wrong with this?

![image](https://user-images.githubusercontent.com/7291672/58315617-6fcb9680-7e44-11e9-833c-67dae5ae1ab8.png)

![image](https://user-images.githubusercontent.com/7291672/58315902-0009db80-7e45-11e9-92fd-b847c6fc1b15.png)

**Comment by xgqfrms** [comment]
# image loader bug ???

![image](https://user-images.githubusercontent.com/7291672/58316219-9f2ed300-7e45-11e9-987c-69511f613e2c.png)

***

**Comment by xgqfrms** [comment]
# image loader ???

> OK

![image](https://user-images.githubusercontent.com/7291672/58317123-bcfd3780-7e47-11e9-9aa5-f71046768ef4.png)

**Comment by egoist** [comment]
use a rollup plugin for this

**Comment by xgqfrms** [comment]
@egoist which plugin, and how to config it, could you show me a demo?

**Comment by egoist** [comment]
@xgqfrms search on npm and read the docs

**Comment by xgqfrms** [comment]
https://www.npmjs.com/search?q=rollup-plugin&page=0

https://www.npmjs.com/package/rollup-plugin-vue

https://www.npmjs.com/package/rollup-plugin-url

**Comment by egoist** [comment]
well don't post unrelated stuff here as this issue is considered resolved.
