### ISSUE TITLE
Issue with scoped module name

### ISSUE THREAD

**Issue by tiaanduplessis** [egoist/bili#21]
First off, great module ❤️ 

Currently when running `bili` with a scoped module name e.g. `@tiaanduplessis/foo` the `@tiaanduplessis` is interpreted as a directory. This results in a sub-directory being created within the `dist` folder e.g. `dist/@tiaanduplessis/foo.js`.  I believe this can quickly be changed by including a check for a scoped module name within the `getDist` function of `get-rollup-options.js` and changing the filename accordingly. Will be happy to create a PR.

**Comment by egoist** [comment]
Sure, please do 👍🏻 maybe just strip away leading `@tiaanduplessis/`

**Comment by tiaanduplessis** [comment]
Yes was thinking the same. Something like: 

```js
if (filename.startsWith('@')) {
    filename = filename.slice(filename.lastIndexOf('/'))
 }
```

should do it

**Comment by egoist** [comment]
Release in 0.17.3
