### ISSUE TITLE
Use uglify-es when Buble is `false`

### ISSUE THREAD

**Issue by olstenlarck** [egoist/bili#27]
You know, Uglify will throw if found modern code (even the latest releases). So using the es package, would make sense if someone disable the Buble transformation, explicitly.

I had same ideas, almost, for the @rolldown, but also built some resolving packages, so it makes customizing and loading pretty awesome. ;] For example loading plugins from both global and local. See how awesome is [resolve-plugins-sync](https://github.com/charlike/resolve-plugins-sync) (may be interested in [resolve-package](https://github.com/charlike/resolve-package), too. used by electron-forge) it can be used for "transforms", "plugins", "presets" and etc, because any of those are just same concepts.
You can try to integrate it here, so resolving logic and passing options to each plugin may be removed.

Good job, anyway.

**Comment by ulivz** [comment]
what exactly does this issue want to point out ? I'm not very clear.

**Comment by charlike** [comment]
what so hard? when buble is disabled, explicitly, the uglifyjs will fail if find some more modern code, so im saying that we should use uglify-es my default.

**Comment by egoist** [comment]
Now we're using `uglify-es` by default. https://egoist.moe/bili/#/api?id=uglifyes
