### ISSUE TITLE
Replacing `process.env.NODE_ENV`

### ISSUE THREAD

**Issue by CrashyBang** [egoist/bili#274]
I am aware of #19 however this functionality appears to have been removed.

I have tried implementing this manually using [`babel-plugin-transform-define`](https://github.com/FormidableLabs/babel-plugin-transform-define) by adding the following to my `babel.config.js` plugins config:

```js
["babel-plugin-transform-define", {
      "process.env.NODE_ENV": "production",
}]
```

However this seems to be having no effect on the compiled output, I could do this via [`@rollup/plugin-replace`](https://github.com/rollup/plugins/tree/master/packages/replace) as demonstrated in this [comment](https://github.com/rollup/rollup/issues/487#issuecomment-177596512) but doing it via `babel` will convert things like `process.env.NODE_ENV === "production"` to `true` in the compiled output which I prefer.

Cheers.

**UPDATE**

Using:

```js
  plugins: {
    vue: true,
    json: true,
    image: true,
    replace: {
      'process.env.NODE_ENV': JSON.stringify( 'production' )
    }
  },
```

Still does not effect compiled output.

**Comment by fi3ework** [comment]
Yes, this options does not exist in v4 (not sure whether exists in v3). Should be fixed.

**Comment by fi3ework** [comment]
@CrashyBang hi, I study the source code a bit and find a workaround to bypass this problem under current version. Bili can resolve custom plugins with options, but rollup-plugin-replace is a built-in plugin of Bili and has some internal options. Here:

```ts
    pluginsOptions.replace = {
      ...config.plugins.replace,
      values: {
        ...Object.keys(env).reduce((res: Env, name) => {
          res[`process.env.${name}`] = JSON.stringify(env[name])
          return res
        }, {}),
        ...(config.plugins.replace && config.plugins.replace.values)
      }
    }
```

in rollup-plugin-replace ([source](https://github.com/rollup/rollup-plugin-replace/blob/master/src/index.js)), values takes precedence over replace so the `plugins.replace` is ignored. But you can use `values` to make it work.

```ts
  plugins: {
    replace: {
      values: {
        'process.env.NODE_ENV': JSON.stringify('production'),
      },
    },
  },
```
BTW, this is really a trip. Should be pointed out in documentation. 😅
