### ISSUE TITLE
Updating deprecated dependencies

### ISSUE THREAD

**Issue by samrith-s** [egoist/bili#284]
Hey,

First off, I absolutely love Bili. I use it at my work and at a lot of other places to build stuff.

Secondly, when I install the package, I get a quite a few warnings about deprecated packages and was wondering if this package is actively maintained and if they will be updated?

Here are the messages in the terminal:
![image](https://user-images.githubusercontent.com/9032162/71917634-cd68e500-3180-11ea-85fc-40f3a652552b.png)

Cheers!

**Comment by fi3ework** [comment]
released in v5
