### ISSUE TITLE
How to develop  plug-in,  like webpack`s devServer , which is convenient for debugging

### ISSUE THREAD

**Issue by loqhcn** [egoist/bili#325]
How to develop  plug-in,  like webpack`s devServer , which is convenient for debugging

**Comment by fi3ework** [comment]
Not sure who the host of the plugin you are talking about. Bili leverages rollup's plugin ecosystem. Maybe this is what you are aiming at? I'll close this issue. Feel free to reopen if there are any follow-up discussions.
