### ISSUE TITLE
Breaking change of ESM format filenames

### ISSUE THREAD

**Issue by chocolateboy** [egoist/bili#363]
**Bili**: 5.0.1, 5.0.4
**Node.js**: v14.0.0
**OS**: Linux (Arch)

As of v5, bili appears to be generating ESM targets (i.e. `--format esm`) as `<filename>.es.js` rather than `<filename>.esm.js`. This looks like a regression as I can't find any reference to it in the release notes or related issues.

Unless the name change is spotted and remediated, this silently breaks the `package.json` `module` entry, and — if the `files` array is used — can result in a package unwittingly being published with a missing ESM bundle.

**Comment by fi3ework** [comment]
This is caused by the upgrading of Rollup from 1.x -> 2.0. Details here https://github.com/rollup/rollup/issues/3370. This is indeed a breaking change and it lands in v5. 4.x still uses `<filename>.esm.js`

**Comment by egoist** [comment]
We should fix that and keep the old behavior https://github.com/egoist/bili/blob/4aae8f0aa682e3bcfc85ddcc5121535008c41847/src/index.ts#L736
