### ISSUE TITLE
Cant build babel-template in umd format 

### ISSUE THREAD

**Issue by promer94** [egoist/bili#418]
I try to use bili to compile babel-template into umd format but failed.
![bilibuilderror.png](https://vip1.loli.net/2020/07/22/METG1kdfjBVIt7i.png)
reproduce repo https://github.com/promer94/bili-babel-template

**Comment by promer94** [comment]
It seems this function cant't be compiled correctly

https://github.com/babel/babel/blob/2bf38fb9149eb514a13bb608e5a9a0c06ad5cacd/packages/babel-types/src/validators/react/isReactComponent.js#L4

**Comment by promer94** [comment]
upgrade babel-template to @babel/template, problem solved

**Comment by egoist** [comment]
Good to know 👍
