### ISSUE TITLE
Error: You have declared using "bundled" babelHelpers, but transforming index.ts resulted in "runtime"

### ISSUE THREAD

**Issue by afontcu** [egoist/bili#538]
Hi! 👋 

I was giving bili a go when I ran into the following issue:

```
Error: You have declared using "bundled" babelHelpers, but transforming /index.ts resulted in "runtime". 
Please check your configuration.
```

My project is created from vue-cli (TS + SCSS). The index file has the usuall stuff for a UI component library: a default export with the `install` function and also all components exported as named exports.

Is there some config I'm missing between the project scaffolded by vue-cli and bili?

Thank you for your time! 👐

**Comment by djkloop** [comment]
@afontcu 


#### you can try

![image](https://user-images.githubusercontent.com/21050914/102485518-b2963480-40a2-11eb-9516-f44611951be0.png)

**Comment by afontcu** [comment]
great, I'll give it a go and come back with the results! Thank you :)

**Comment by afontcu** [comment]
worked like a charm, thank you! ❤️
