### ISSUE TITLE
Can't make run in browser

### ISSUE THREAD

**Issue by artyprog** [egoist/bili#55]
Hello,

I have successfully compiled un UMD format,  but I can not make  it run in browser

```html
<!DOCTYPE html>
<html lang="en">

<head>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.13/vue.min.js"></script>
	<script src="./dist/index.js"></script>
</head>
<body>
	<div id="app">
		<my-component></my-component>
	</div>
	<script>
		window.onload = function () {

			new Vue({
				el: "#app",
				components: {
					MyComponent
				}
			})
		}
	</script>
</body>
</html>
```

I got the followinn error :  Vue.component is not a function

regards

**Comment by egoist** [comment]
@artyprog can you provide a repo?

**Comment by artyprog** [comment]
Thanks here it is

https://github.com/artyprog/testbili

**Comment by egoist** [comment]
@artyprog you exported a Vue plugin but didn't install it

**Comment by artyprog** [comment]
You mean I have to insert Vue.use(MyComponent) ?
in the html file

**Comment by egoist** [comment]
Yeah, that's how a user would use your library since you exported a Vue plugin. `window.MyComponent` is actually the exported function, however you can automatically it when user is using it in browser.

Change your `index.js` to:

```js
import Component from './MyComponent.vue'
export default Vue => Vue.component(Component.name, Component)

if (typeof window !== 'undefined' && window.Vue) {
	Vue.component(Component.name, Component)
}
```

**Comment by artyprog** [comment]
I must be 'dumb' i still got the same error ....

**Comment by egoist** [comment]
what error?

**Comment by egoist** [comment]
oh well, don't add it to `components`, since it's a plugin.

**Comment by artyprog** [comment]
Thank you very very much, it works now :-)
Regards
