### ISSUE TITLE
Vue component not been transpiled down to ES5

### ISSUE THREAD

**Issue by VitorLuizC** [egoist/bili#60]
I'm updating bili in one of my projects which is a Vue component and stuck into a issue. All JavaScript modules are correct transpiled but Vue component isn't.

This is a diff from bundled Vue component with Bili version 0.19.x and 1.5.x.

<img
  width="815"
  alt="Diff between module bundled with version 0.19 and right now with 1.5"
  title="Diff between module bundled with version 0.19 and right now with 1.5"
  src="https://user-images.githubusercontent.com/9027363/34917089-d0cd912e-f928-11e7-8623-94320d2b0cfa.png"
/>

I'm running `bili src/DataTable.vue` with the `bili.config.js` file below.
```js
const { name } = require('./package')

module.exports = {
  name,
  banner: true,
  format: ['umd', 'umd-min', 'cjs', 'es'],
  plugins: ['vue'],
  vue: {
    css: `dist/vue-data-tablee.css`
  }
}

```

That's the component I'm trying to build with Bili 1.5.x on the branch I'm working on it.
https://github.com/VitorLuizC/vue-data-tablee/tree/fixture/upgrade-dependencies

**Comment by egoist** [comment]
OK, I found the reason, the built-in `buble/babel` plugin is only transforming `.jsx?$` files

**Comment by egoist** [comment]
It works fine now in `v1.5.8`
