### ISSUE TITLE
How disable `preferBuiltins` ?

### ISSUE THREAD

**Issue by edDimensi** [egoist/bili#61]
Hi, i can't understand from doc

**Comment by egoist** [comment]
there's no option for this, why do you need it?

**Comment by edDimensi** [comment]
I use url package from npm and rollup do this
![screenshot_20180120_194028](https://user-images.githubusercontent.com/11390039/35185724-c689811e-fe19-11e7-8fe9-77f7a69ca88e.png)

**Comment by egoist** [comment]
Seems you're using an outdated version of bili?

**Comment by edDimensi** [comment]
1.6.5

**Comment by edDimensi** [comment]
Sorry for offtopic, but how change prefix in bili? I don't like prefix `.m.js` for es modules

**Comment by egoist** [comment]
You can use [filename](https://egoist.moe/bili/#/api?id=filename) but I will change it back to `.es` in 2.0

**Comment by egoist** [comment]
`preferBuiltins` is an option for `rollup-plugin-node-resolve` and you can set it in this way:

```bash
bili --nodeResolve.preferBuiltIns
```

Haven't documented this though.

**Comment by edDimensi** [comment]
not working

**Comment by egoist** [comment]
hmm there's a typo, should be:

```bash
bili --nodeResolve.preferBuiltins
```
