### ISSUE TITLE
can not be packaged when import css by style tag

### ISSUE THREAD

**Issue by sinchang** [egoist/bili#65]
when import by

```
<style src="../node_modules/dplayer/dist/DPlayer.min.css"></style>
```
repo: https://github.com/MoePlayer/vue-dplayer

**Comment by egoist** [comment]
This is related to rollup-plugin-vue I think.

**Comment by egoist** [comment]
btw I think you don't really need to use `.vue` file in `vue-dplayer` 😄

**Comment by sinchang** [comment]
Thanks. use vue jsx fixed
