### ISSUE TITLE
Use babel@7

### ISSUE THREAD

**Issue by egoist** [egoist/bili#73]
- [x] migrate `src/babel.js`
- [x] Use `@babel/core` in Jest

**Comment by VladShcherbin** [comment]
@egoist hey, is it somehow possible to use `bili` now with babel@7? This `yarn bili --js babel` gives an error:

```terminal
Error: Cannot find module 'babel-preset-env'
```

**Comment by egoist** [comment]
@VladShcherbin I just published `v2.2.7` which fixed this error, so `bili --js babel` should work now for you but it's using babel 6.

I also published `v3.0.0-beta.0` under `next` tag, run `yarn add bili@next --dev` to get it, it uses babel v7 by default so running `bili` will use babel v7 instead of buble.

**Comment by VladShcherbin** [comment]
@egoist thanks.

Is it possible to configure `bili` same way as [this config](https://github.com/VladShcherbin/dot-prop-wild/blob/master/rollup.config.js) but using only cli? Basically it produces 2 formats (cjs, es) for 2 targets (node, browser), removes comments in code and runs prettier after.

**Comment by egoist** [comment]
Done and published v3.
