### ISSUE TITLE
Add possibility to bundle pure es6 package

### ISSUE THREAD

**Issue by vladshcherbin** [egoist/bili#79]
According to [this](https://github.com/egoist/bili/blob/master/src/babel.js#L72), the bundled file will be transpiled to `ie9`.

What about use-case when you don't want to transpile source code, want to bundle es6 code and let developer to decide, to what environment transpile his app. Since there are already browsers which have good support of es6, some users might not even need to transpile.

**Comment by egoist** [comment]
Sure with `--no-js` or `js: false`.

**Comment by vladshcherbin** [comment]
@egoist yes, but this will turn off babel/buble.

What if I want to use babel, but don't want to transpile to es5? For example, if I want to use only `@babel/plugin-proposal-class-properties`.

**Comment by egoist** [comment]
just use your `.babelrc`

**Comment by vladshcherbin** [comment]
@egoist let me show you, here is an [example repo](https://github.com/vladshcherbin/experiments/tree/master/bili)

In [babelrc](https://github.com/vladshcherbin/experiments/blob/master/bili/.babelrc.js) I only have this:

```js
module.exports = {
  plugins: [
    '@babel/plugin-proposal-class-properties'
  ]
}
```

But the [bundled version](https://github.com/vladshcherbin/experiments/blob/master/bili/dist/bili.es.js) is still transpiled to es5.

**Comment by egoist** [comment]
hmm bili uses buble by default, to use babel you need `--js babel`

**Comment by egoist** [comment]
You can set `presets` to an empty array or `undefined` to override defaults:

```json
{
	"bili": {
		"babel": {
			"presets": []
		}
	}
}
```

**Comment by vladshcherbin** [comment]
@egoist this does the job, thanks.

Is it possible to add `.bilirc.js` config file support to match babel/eslint?
