### ISSUE TITLE
Disable default babel config when `.babelrc` was found

### ISSUE THREAD

**Issue by egoist** [egoist/bili#89]
Also add the config path to debug log: `logger.debug('babel config', path)`

Also #87 is no longer needed.

**Comment by ulivz** [comment]
I met this problem, so I remove the existing `.babelrc` when I run build script.

**Comment by egoist** [comment]
@ulivz you can disable that file by passing `--no-babel.babelrc` flag

**Comment by ulivz** [comment]
@egoist Got it, thanks. I think this might be a problem with Babel upgrade.

I found the old babel config is not fit for babel7 💔.
