### ISSUE TITLE
Allow to disable JS transformation

### ISSUE THREAD

**Issue by Swizz** [egoist/bili#9]
At the moment `js: false` result to the use of Bublé. 

How if I want to use bili to quickly bundle and keeping my own es2015 transformation workflow ?

**Comment by egoist** [comment]
Now you can set `js: false` or use `--no-js` to disable it, but why would you use a custom es2015 transformation workflow instead of using rollup plugin? like `js: 'babel'`

**Comment by Swizz** [comment]
Because I just want a bundler. Not a build tool. 
This is only a personal issue. 

Thank you for this feature.
